id is:u3w63hxn
Launching wandb...
[36m(RLRunner pid=664643)[39m RGB image saved to test_images/step_000.png
[36m(RLRunner pid=664644)[39m Exception raised in creation task: The actor died because of an error raised in its creation task, [36mray::RLRunner.__init__()[39m (pid=664644, ip=10.1.123.172, actor_id=9259ffed334577dfaab29bed01000000, repr=<runner.RLRunner object at 0x7f48c39e8fd0>)
[36m(RLRunner pid=664644)[39m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(RLRunner pid=664644)[39m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(RLRunner pid=664644)[39m   File "/home/ubuntu/LNS2-RL/runner.py", line 286, in __init__
[36m(RLRunner pid=664644)[39m     super().__init__(meta_agent_id)
[36m(RLRunner pid=664644)[39m   File "/home/ubuntu/LNS2-RL/runner.py", line 35, in __init__
[36m(RLRunner pid=664644)[39m     self.valid_actions, self.obs, self.vector, self.train_valid = self.rl_local_reset_env(True)
[36m(RLRunner pid=664644)[39m                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(RLRunner pid=664644)[39m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(RLRunner pid=664644)[39m   File "/home/ubuntu/LNS2-RL/runner.py", line 158, in rl_local_reset_env
[36m(RLRunner pid=664644)[39m     self.env._local_reset(self.local_num_agent, first_time)
[36m(RLRunner pid=664644)[39m   File "/home/ubuntu/LNS2-RL/mapf_gym.py", line 645, in _local_reset
[36m(RLRunner pid=664644)[39m     new_agents = random.sample(range(self.global_num_agent), local_num_agents)
[36m(RLRunner pid=664644)[39m                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(RLRunner pid=664644)[39m   File "/home/ubuntu/miniconda/envs/lns2+RL/lib/python3.11/random.py", line 456, in sample
[36m(RLRunner pid=664644)[39m     raise ValueError("Sample larger than population or is negative")
[36m(RLRunner pid=664644)[39m ValueError: Sample larger than population or is negative
Saving Final Model !